---
- hosts: jenkins-slave
  become: true 
  tasks: 
  - name: Update yum packages
    yum:
      name: '*'
      state: latest

  - name: Install Java 17
    yum:
      name: java-17-amazon-corretto
      state: present

  - name: download maven packages 
    get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
      dest: /opt

  - name: extract maven packages 
    unarchive:
      src: /opt/apache-maven-3.9.9-bin.tar.gz
      dest: /opt 
      remote_src: yes

