---
- hosts: jenkins-slave
  become: true 
  tasks: 
  - name: Update yum packages
    yum:
      name: '*'
      state: latest

  - name: Install Java 17
    yum:
      name: java-17-amazon-corretto
      state: present

  - name: download maven packages 
    get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
      dest: /opt

  - name: extract maven packages 
    unarchive:
      src: /opt/apache-maven-3.9.9-bin.tar.gz
      dest: /opt 
      remote_src: yes
  
  - name: Install git
    yum:
      name: git
      state: present
    tags: install_git

  - name: check version
    shell: git --version
    tags: install_git
    register: git_version
    
  - name: print git version
    debug:
      msg: "{{ git_version.stdout }}"
    tags: install_git

  - name: Install Docker
      yum:
        name: docker
        state: present

  - name: Start and enable Docker service
    service:
      name: docker
      state: started


