---
- name: Install Jenkins on Amazon Linux
  hosts: jenkins-master
  become: true
  tasks:
    - name: Install Java 17 (Jenkins requires Java)
      yum:
        name: java-17-amazon-corretto
        state: present

    - name: Add Jenkins repository
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import the Jenkins GPG key
      command: rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
    
    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Enable and start Jenkins service
      systemd:
        name: jenkins
        enabled: yes
        state: started
    
    - name: enable jenkins to start at boot time 
        service: 
          name: jenkins 
          enabled: yes 