---
- hosts: jenkins-slave
  become: true 
  tasks: 
  - name: Update yum packages
    yum:
      name: '*'
      state: latest

  - name: Install Java 17
    yum:
      name: java-17-amazon-corretto
      state: present

  - name: download maven packages 
    get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz
      dest: /opt

  - name: extract maven packages 
    unarchive:
      src: /opt/apache-maven-3.9.9-bin.tar.gz
      dest: /opt 
      remote_src: yes
  
  - name: Install git
    yum:
      name: git
      state: present
    tags: install_git

  - name: check version
    shell: git --version
    tags: install_git
    register: git_version
    
  - name: print git version
    debug:
      msg: "{{ git_version.stdout }}"
    tags: install_git
    ignore_errors: yes

  - name: Install Docker
    yum:
      name: docker
      state: present

  - name: Start and enable Docker service
    service:
      name: docker
      state: started
  
  - name: check docker version
    shell: docker --version
    register: docker_version
    
  - name: print docker version
    debug:
      msg: "{{ docker_version.stdout }}"
    ignore_errors: yes

  - name: Verify Docker service status explicitly
    command: systemctl is-active docker
    register: docker_status

  - name: Display Docker service status
    debug:
      msg: "Docker service is {{ docker_status.stdout }}"

  - name: give 777 permissions on /var/run/docker.sock
    file: 
      path: /var/run/docker.sock
      state: file 
      mode: 0777
      
  - name: start docker on boot time 
    service: 
      name: docker 
      enabled: yes

  - name: Download kubectl binary
    get_url:
      url: "https://s3.us-west-2.amazonaws.com/amazon-eks/1.32.0/2024-12-20/bin/linux/amd64/kubectl"
      dest: /usr/local/bin/kubectl
      mode: '0755'

  - name: Validate kubectl installation
    shell: kubectl version --client
    register: kubectl_version
    ignore_errors: no

  - name: Display kubectl version
    debug:
      msg: "{{ kubectl_version.stdout }}"